/*!

=========================================================
* Chong Lua Dao
=========================================================

* Product Page: https://chongluadao.vn/
* Copyright 2021 https://chongluadao.vn/
* Coded by ChongLuaDao

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
!function(e){var t={};function n(s){if(t[s])return t[s].exports;var i=t[s]={i:s,l:!1,exports:{}};return e[s].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=e,n.c=t,n.d=function(e,t,s){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:s})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var s=Object.create(null);if(n.r(s),Object.defineProperty(s,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var i in e)n.d(s,i,function(t){return e[t]}.bind(null,i));return s},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=3)}({3:function(e,t){const n=browser.runtime.getBackgroundPage(),s={"-1":"#28a745",0:"#ffeb3c",1:"#cc0000"};[...document.getElementsByClassName("collapsible")].forEach(e=>{e.addEventListener("click",(function(){this.classList.toggle("active");const e=this.nextElementSibling;e.style.maxHeight?e.style.maxHeight=null:e.style.maxHeight=e.scrollHeight+"px"}))}),browser.tabs.query({currentWindow:!0,active:!0},([e])=>{const t=e.id,i=new URL(e.url),o=i.hostname;if(!["https:","http:"].includes(i.protocol))return $("#pluginBody").hide(),void $("#domain_url").text(o);if(n.isWhiteList[e.id]==o)$("#pluginBody").hide(),$("#isSafe").show(),$("#isSafe .site-url").text(o),browser.browserAction.setIcon({path:"../assets/cldvn128.png",tabId:t});else if(n.isBlocked[e.id]==o)$("#pluginBody").hide(),$("#isPhishing").show(),$("#isPhishing .site-url").text(n.isBlocked[e.id]),browser.browserAction.setIcon({path:"../assets/cldvn_red.png",tabId:t});else{const t=n.results[e.id],i=n.isPhish[e.id],r=n.legitimatePercents[e.id];for(const e in t){const n=document.createElement("li");n.textContent=e,n.style.backgroundColor=s[t[e]];document.getElementById("features").appendChild(n)}const a=i?"Website này có thể không an toàn.":"Website này có thể an toàn.",c=document.getElementById("site_score"),l=document.getElementById("percentage_content"),d=document.getElementById("site_msg");l.classList.add("p"+parseInt(r)),i?(l.classList.add("orange"),c.classList.add("warning"),d.classList.add("warning")):(c.classList.add("safe"),d.classList.add("safe"));const u=parseInt(r);$("#site_msg").text(isNaN(u)?"...":a),$("#site_score").text(isNaN(u)?"...":parseInt(r)-1+"%"),$("#domain_url").text(o)}})}});